// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkhawnmbfmbnzspfgkje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpraGF3bm1iZm1ibnpzcGZna2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODU5MzYsImV4cCI6MjA2NDA2MTkzNn0.-qUB2hiqWuUaesE0ik0YI-Clb9_9dKM3h59AuyGeoDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});